[tool.poetry]
name = "pytorch-playground"
version = "0.1.0"
description = ""
authors = ["Alexandre Maros <alehstk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = {version = "^2.3.0+cpu", source = "pytorch_cpu"}
numpy = "^1.26.4"
jupyterlab = "^4.1.8"
notebook = "^7.1.3"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.2"


[[tool.poetry.source]]
name = "pytorch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
